name: bolsa_de_oportunidades_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_core: ^3.8.0
  flutter_local_notifications: ^14.0.0
  firebase_messaging: ^15.1.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  http: ^1.2.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon" # Especifica que solo estás generando íconos para Android
  ios: false               # Desactiva explícitamente iOS para evitar el mensaje
  image_path: "assets/icon/icon.png"
